spring:
  profiles: default

  freemarker:
    cache: false

  jackson:
    mapper:
      default_view_inclusion: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  jpa:
    database: h2
    show-sql: true
    hibernate:
      connection:
        charSet: UTF-8
      ddl-auto: create

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 50
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type


  datasource:
    url: jdbc:h2:mem:osoridb;DB_CLOSE_ON_EXIT=FALSE;AUTOCOMMIT=OFF
    username: sa
    password:

  h2:
    console:
      enabled: true

server:
  port: 5000

management:
  shell:
    ssh:
      enabled: true
      port: 10001
    auth:
      simple:
        user:
          name: osori
          password: osori

logging:
  level:
    org.springframework.web: trace
    org.springframework.boot: trace
    org.hibernate: error
    org.hibernate.type: trace
    in.woowa.platform.osori.admin: trace

---

spring:
  profiles: h2

  freemarker:
    cache: false

  jackson:
    mapper:
      default_view_inclusion: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  jpa:
    database: h2
    show-sql: true
    hibernate:
      connection:
        charSet: UTF-8
      ddl-auto: create

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 50
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type


  datasource:
    url: jdbc:h2:./db/:osoridb;DB_CLOSE_ON_EXIT=FALSE;AUTOCOMMIT=OFF
    username: sa
    password:

  h2:
    console:
      enabled: true

server:
  port: 5000

management:
  shell:
    ssh:
      enabled: true
      port: 10001
    auth:
      simple:
        user:
          name: osori
          password: osori

logging:
  level:
    org.springframework.web: debug
    org.springframework.boot: debug
    org.hibernate: error
    in.woowa.platform.osori.admin: debug

---
spring:
  profiles: mysql

  freemarker:
    cache: false

  jackson:
    mapper:
      default_view_inclusion: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      connection:
        charSet: UTF-8
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.default_batch_fetch_size: 50
      org.hibernate.envers.audit_table_suffix: _history
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type

  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 200
      pool-name: SpringBootHikariCP
    url:
    username:
    password:
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 150
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    org.springframework.web: info
    org.springframework.boot: info
    org.hibernate: error
    in.woowa.platform.osori.admin: info

server:
  port: 5000
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

